<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Lwt_timeout (lwt.Lwt_timeout)</title><link rel="stylesheet" href="../../_odoc-theme/odoc.css"/><meta charset="utf-8"/><meta name="generator" content="odoc v1.1.1-1122-g40586318"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><script src="../../highlight.pack.js"></script><script>hljs.initHighlightingOnLoad();</script></head><body><div class="content"><header><nav><a href="../index.html">Up</a> â€“ <a href="../index.html">lwt</a> &#x00BB; Lwt_timeout</nav><h1>Module <code>Lwt_timeout</code></h1><p>Cancelable timeouts.</p></header><dl><dt class="spec type" id="type-t"><a href="#type-t" class="anchor"></a><code><span class="keyword">type</span> t</code></dt></dl><dl><dt class="spec value" id="val-create"><a href="#val-create" class="anchor"></a><code><span class="keyword">val</span> create : int <span>&#45;&gt;</span> <span>(unit <span>&#45;&gt;</span> unit)</span> <span>&#45;&gt;</span> <a href="index.html#type-t">t</a></code></dt><dd><p><code>Lwt_timeout.create n f</code> creates a new timeout object with duration <code>n</code> seconds. <code>f</code> is the <em>action</em>, a function to be called once the timeout expires. <code>f</code> should not raise exceptions.</p><p>The timeout is not started until <a href="index.html#val-start"><code>Lwt_timeout.start</code></a> is called on it.</p></dd></dl><dl><dt class="spec value" id="val-start"><a href="#val-start" class="anchor"></a><code><span class="keyword">val</span> start : <a href="index.html#type-t">t</a> <span>&#45;&gt;</span> unit</code></dt><dd><p>Starts the given timeout.</p><p>Starting a timeout that has already been started has the same effect as stopping it, and then restarting it with its original duration. So, suppose you have <code>timeout</code> with a duration of three seconds, which was started two seconds ago. The next call to its action is scheduled for one second in the future. Calling <code>Lwt_timeout.start timeout</code> at this point cancels this upcoming action call, and schedules a call three seconds from now.</p></dd></dl><dl><dt class="spec value" id="val-stop"><a href="#val-stop" class="anchor"></a><code><span class="keyword">val</span> stop : <a href="index.html#type-t">t</a> <span>&#45;&gt;</span> unit</code></dt><dd><p>Stops (cancels) the given timeout.</p></dd></dl><dl><dt class="spec value" id="val-change"><a href="#val-change" class="anchor"></a><code><span class="keyword">val</span> change : <a href="index.html#type-t">t</a> <span>&#45;&gt;</span> int <span>&#45;&gt;</span> unit</code></dt><dd><p>Changes the duration of the given timeout.</p><p>If the timeout has already been started, it is stopped, and restarted with its new duration. This is similar to how <a href="index.html#val-start"><code>Lwt_timeout.start</code></a> works on a timeout that has already been started.</p></dd></dl><dl><dt class="spec value" id="val-set_exn_handler"><a href="#val-set_exn_handler" class="anchor"></a><code><span class="keyword">val</span> set_exn_handler : <span>(exn <span>&#45;&gt;</span> unit)</span> <span>&#45;&gt;</span> unit</code></dt><dd><p><code>Lwt_timeout.set_exn_handler f</code> sets the handler to be used for exceptions raised by timeout actions. Recall that actions are not allowed to raise exceptions. If they do raise an exception <code>exn</code> despite this, <code>f exn</code> is called.</p><p>The default behavior of <code>f exn</code>, set by <code>Lwt_timeout</code> on program startup, is to pass <code>exn</code> to <code>!</code><span class="xref-unresolved" title="unresolved reference to &quot;Lwt.async_exception_hook&quot;"><code>Lwt</code>.async_exception_hook</span>. The default behavior of <em>that</em> is to terminate the process.</p></dd></dl></div></body></html>